project:
  type: website
  output-dir: docs

website:
  title: David M. Waguespack
  navbar: false

  comments:
    giscus:
      repo: davewaguespack/website
      loading: lazy
      theme: dark 

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

